### ISSUE TITLE
Add disable global security

### ISSUE THREAD

**Issue by norguhtar** [get-net/http-openapi#5]
When global security enabled it can be disabled by 

```yaml
  /ping:
    get:
      summary: Checks if the server is running
      security: []   # No security
      responses:
        '200':
          description: Server is up and running
        default:
          description: Something is wrong
```
https://swagger.io/docs/specification/authentication/

It shold work in our implementation

**Comment by ghost** [comment]
Fixed [here](https://github.com/get-net/http-openapi/commit/5cd44cc29d7af9001f9e1a455fa3d1ff863c24fa)
